=== kumakumita/hello-word/Examen/Examen.dtd
<!--Entidades fabricante-->
<!ENTITY f1 "Renault">
<!ENTITY f2 "Wolkswagen">

<!--Entidades extras-->
<!ENTITY extraRenault SYSTEM "Extras/extrasRenault.txt">
<!ENTITY extraWolkswagen SYSTEM "Extras/extrasWolkswagen.txt">

<!--Entidades foto-->
<!ENTITY fotoRenault SYSTEM "fotoRenault.jpg" NDATA jpg>
<!ENTITY fotoWolkswagen SYSTEM "fotoWolkswagen.jpg" NDATA jpg>
<!NOTATION jpg SYSTEM "visorjpg.exe">

<!--Entidades de parametro-->
<!ENTITY % p "#REQUIRED">
<!ENTITY % i "#IMPLIED">




<!--Elemento vehiculos-->
<!ELEMENT vehiculos (vehiculo)+>

<!--Elemento vehiculo-->
<!ELEMENT vehiculo (modelo, caracteristicas, precio)>
  <!ATTLIST vehiculo 
                                        bastidor ID %p;
                                        foto ENTITY %p;>

<!--Elemento modelo-->
<!ELEMENT modelo (fabricante, anno, nombreComercial, nombreTecnico?)>
    <!ELEMENT fabricante (#PCDATA)>
    <!ELEMENT anno (#PCDATA)>
    <!ELEMENT nombreComercial (#PCDATA)>
      <!ATTLIST nombreComercial idNC ID %p;>
      
    <!ELEMENT nombreTecnico (#PCDATA)>
      <!ATTLIST nombreTecnico idNT IDREF #REQUIRED>

<!--Elemento caracteristicas-->
<!ELEMENT caracteristicas (cilindrada, emisiones, potencia, extras)>
    <!ATTLIST caracteristicas 
                                                    combustible (diesel | gasolina | otro) "diesel" 
                                                    color (blanco | rojo | azul | gris | negro) "negro">
    
    <!ELEMENT cilindrada (#PCDATA)>
    <!ELEMENT emisiones (#PCDATA)>
    <!ELEMENT potencia (#PCDATA)>
    <!ELEMENT extras (#PCDATA)>

<!--Elemento precio-->
  <!ELEMENT precio (#PCDATA)>
    <!ATTLIST precio oferta (SI | NO) "SI">

=== kumakumita/hello-word/Examen/Examen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vehiculos SYSTEM "Examen.dtd">

<vehiculos>

    <vehiculo bastidor="B1234" foto="fotoRenault">
       <modelo>
           <fabricante>&f1;</fabricante>
           <anno>2014</anno>
           <nombreComercial idNC="Re">Clio</nombreComercial>
           <nombreTecnico idNT="Re">Clio 5p elegante full Luxury premium plus</nombreTecnico>
       </modelo>
       
       <caracteristicas combustible="gasolina" color="rojo">
           <cilindrada>1200 cc</cilindrada>
           <emisiones>95 mg</emisiones>
           <potencia>65 CV</potencia>
           <extras>&extraRenault;</extras>
       </caracteristicas>
       
       <precio oferta="SI">7800</precio>
    </vehiculo>
    
    
    <vehiculo bastidor="B5678" foto="fotoWolkswagen">
       <modelo>
          <fabricante>&f2;</fabricante>
          <anno>2013</anno>
          <nombreComercial idNC="Wo">Polo</nombreComercial>
       </modelo> 
       
       <caracteristicas>
          <cilindrada>1398 cc</cilindrada>
           <emisiones>125 mg</emisiones>
           <potencia>58kwh</potencia>
           <extras>&extraWolkswagen;</extras>
       </caracteristicas>
       
       <precio oferta="NO">8995</precio>
    </vehiculo>
</vehiculos>
